In [1]:
import pandas as pd

file = pd.read_csv("CovidMalletDataFrame.csv", sep=',', parse_dates=['dData'])
file.head()

   dDescartados  dNotificados  dMonitorados  dSuspeitos  dPositivos  dRecuperados  dObitos  dAtuais      dData
0           507           589            24          24          42            40        2       16 2020-01-08
1           704           765            17          11          50            42        2        6 2020-01-09
2           809           891            10           9          73            70        2        1 2020-01-10
3           704           771            20          17          50            45        2        3 2020-02-09
4          1049          1177            24          22         106           102        2        2 2020-02-12

In [2]:
file['dData'] = pd.to_datetime(file.dData)
file['dData'] = file['dData'].dt.strftime('%m/%d/%Y')
file.sort_values('dData', inplace=True)
file
file.to_csv(r'file.csv', index = False) # exporta para csv

In [3]:
i = len(file.dAtuais) -1
file.loc[[i]]

     dDescartados  dNotificados  dMonitorados  dSuspeitos  dPositivos  dRecuperados  dObitos  dAtuais       dData
104           703           761            14           8          50            42        2        6  08/31/2020

In [4]:
file

    dDescartados  dNotificados  dMonitorados  dSuspeitos  dPositivos  dRecuperados  dObitos  dAtuais       dData
0            507           589            24          24          42            40        2       16  01/08/2020
1            704           765            17          11          50            42        2        6  01/09/2020
2            809           891            10           9          73            70        2        1  01/10/2020
3            704           771            20          17          50            45        2        3  02/09/2020
4           1049          1177            24          22         106           102        2        2  02/12/2020
..           ...           ...           ...         ...         ...           ...      ...      ...         ...
38           581           650            12          11          43            40        2       16  12/08/2020
39           940          1046            28          23          83            76        2        5  12/11/2020
48          1080          1200             8           3         117           110        2        5  12/15/2020
52          1080          1210            18          12         118           110        2        6  12/16/2020
60          1086          1219            21          12         121           110        2        9  12/18/2020

[105 rows x 9 columns]